import React from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable, Image, Linking } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Ionicons } from '@expo/vector-icons';

const SITE='https://project-startup-psi.vercel.app/';
const WA='https://wa.me/919989698152';
const properties=[
 {id:'1',title:'Premium Residential Plot',type:'Residential Plot',location:'Ramanthapur, Hyderabad',price:'Contact for price',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1000'},
 {id:'2',title:'Independent House',type:'Independent House',location:'Hyderabad, Telangana',price:'Contact for price',image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000'},
 {id:'3',title:'Commercial Property',type:'Commercial',location:'Greater Hyderabad',price:'Contact for price',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1000'}
];
export default function App(){
 const open=(u:string)=>Linking.openURL(u);
 return <View style={s.root}><StatusBar style="light"/><ScrollView showsVerticalScrollIndicator={false}>
  <View style={s.hero}><View style={s.top}><View><Text style={s.brand}>VRV ESTATES</Text><Text style={s.sub}>HYDERABAD PROPERTIES</Text></View><Pressable onPress={()=>open(SITE)} style={s.icon}><Ionicons name="globe-outline" size={21} color="#fff"/></Pressable></View>
   <Text style={s.location}>RAMANTHAPUR • HYDERABAD • TELANGANA</Text><Text style={s.h1}>Premium Properties{`\n`}<Text style={s.gold}>& Land, Curated.</Text></Text><Text style={s.desc}>Discover thoughtfully selected homes, residential plots and commercial properties across Hyderabad — with direct, transparent guidance from VRV Estates.</Text>
   <View style={s.actions}><Pressable style={s.primary} onPress={()=>open(SITE+'#all-properties')}><Text style={s.primaryText}>Explore Properties</Text></Pressable><Pressable style={s.secondary} onPress={()=>open('tel:+919989698152')}><Ionicons name="call" size={18} color="#fff"/><Text style={s.secondaryText}>Call</Text></Pressable><Pressable style={s.whatsapp} onPress={()=>open(WA)}><Ionicons name="logo-whatsapp" size={18} color="#fff"/></Pressable></View>
  </View>
  <View style={s.body}><Text style={s.kicker}>FEATURED PROPERTIES</Text><Text style={s.title}>Find a place worth owning.</Text>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:16,paddingBottom:10}}>{properties.map(p=><Pressable key={p.id} style={s.card} onPress={()=>open(SITE+'#all-properties')}><Image source={{uri:p.image}} style={s.cardImg}/><View style={s.cardBody}><Text style={s.type}>{p.type}</Text><Text style={s.cardTitle}>{p.title}</Text><Text style={s.loc}><Ionicons name="location-outline" size={14}/> {p.location}</Text><Text style={s.price}>{p.price}</Text></View></Pressable>)}</ScrollView>
   <Text style={[s.kicker,{marginTop:28}]}>EXPLORE BY CATEGORY</Text><Text style={s.title}>Property, your way.</Text><View style={s.grid}>{['Luxury Homes','Residential Plots','Commercial','Independent Houses'].map((x,i)=><Pressable key={x} style={s.cat} onPress={()=>open(SITE+'#all-properties')}><Ionicons name={['home-outline','map-outline','business-outline','key-outline'][i] as any} size={25} color="#c9a86a"/><Text style={s.catText}>{x}</Text></Pressable>)}</View>
   <View style={s.about}><Text style={s.kicker}>TRUSTED GUIDANCE</Text><Text style={s.title}>Meet Rahul Gabbeta.</Text><Text style={s.aboutText}>VRV Estates simplifies property acquisition across Ramanthapur and greater Hyderabad. Our focus is personalized service built on clarity and trust.</Text><View style={s.actions}><Pressable style={s.primary} onPress={()=>open('tel:+919989698152')}><Text style={s.primaryText}>Call Rahul</Text></Pressable><Pressable style={s.secondaryDark} onPress={()=>open(WA)}><Text style={s.secondaryDarkText}>Send Enquiry</Text></Pressable></View></View>
   <View style={s.footer}><Text style={s.brand}>VRV ESTATES</Text><Text style={s.footerText}>Ramanthapur, Hyderabad, Telangana 500013</Text><Text style={s.footerText}>Rahul Gabbeta • +91 9989698152</Text><Text style={s.copy}>© VRV Estates. All rights reserved.</Text></View>
  </View>
 </ScrollView><Pressable style={s.fab} onPress={()=>open(WA)}><Ionicons name="logo-whatsapp" size={28} color="#fff"/></Pressable></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#0b0b0b'},hero:{backgroundColor:'#0b0b0b',padding:22,paddingTop:55,paddingBottom:30},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:22,fontWeight:'800',letterSpacing:2,color:'#fff'},sub:{fontSize:8,letterSpacing:2,color:'#c9a86a',marginTop:2},icon:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:'#333',alignItems:'center',justifyContent:'center'},location:{fontSize:9,letterSpacing:1.5,color:'#8f8f8f',marginTop:35},h1:{fontSize:40,lineHeight:45,fontWeight:'800',color:'#fff',marginTop:16},gold:{color:'#c9a86a'},desc:{fontSize:14,lineHeight:22,color:'#aaa',marginTop:15},actions:{flexDirection:'row',gap:9,marginTop:22,alignItems:'center'},primary:{backgroundColor:'#c9a86a',paddingHorizontal:17,paddingVertical:13,borderRadius:8},primaryText:{fontWeight:'800',color:'#111'},secondary:{borderWidth:1,borderColor:'#555',paddingHorizontal:15,paddingVertical:12,borderRadius:8,flexDirection:'row',gap:6,alignItems:'center'},secondaryText:{color:'#fff',fontWeight:'700'},whatsapp:{width:45,height:45,borderRadius:8,backgroundColor:'#1b8d53',alignItems:'center',justifyContent:'center'},body:{padding:22,backgroundColor:'#111'},kicker:{fontSize:10,letterSpacing:2,color:'#c9a86a',fontWeight:'700'},title:{fontSize:28,fontWeight:'800',color:'#fff',marginTop:8,marginBottom:18},card:{width:270,backgroundColor:'#1a1a1a',borderRadius:14,overflow:'hidden'},cardImg:{height:170,width:'100%'},cardBody:{padding:15},type:{fontSize:10,color:'#c9a86a',textTransform:'uppercase',fontWeight:'700'},cardTitle:{fontSize:18,fontWeight:'800',color:'#fff',marginTop:5},loc:{color:'#999',fontSize:12,marginTop:8},price:{color:'#fff',fontWeight:'800',marginTop:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},cat:{width:'47%',minHeight:105,backgroundColor:'#1a1a1a',borderRadius:12,padding:16,justifyContent:'space-between'},catText:{color:'#fff',fontWeight:'700'},about:{marginTop:30,padding:22,backgroundColor:'#191919',borderRadius:16},aboutText:{color:'#aaa',lineHeight:22,fontSize:14},secondaryDark:{borderWidth:1,borderColor:'#555',paddingHorizontal:16,paddingVertical:12,borderRadius:8},secondaryDarkText:{color:'#fff',fontWeight:'700'},footer:{paddingVertical:35,alignItems:'center'},footerText:{color:'#888',marginTop:8,fontSize:12},copy:{color:'#555',marginTop:20,fontSize:11},fab:{position:'absolute',right:20,bottom:25,width:58,height:58,borderRadius:29,backgroundColor:'#1b8d53',alignItems:'center',justifyContent:'center',elevation:8}}
);
